title: Austin McGahan # your name (or website title) here
logo: images/profile_photo.jpg?raw=True # your photo (or logo) here
description: >
  **Operations Research Analyst**  
  [M.S. Operations Research](https://nps.edu/web/or/operations-analysis-360) 
  Naval Postgraduate School(June 2024) 

  [M.S. Engineering Management](https://emse.mst.edu/academicprograms/engineeringmanagement/graduate/)  
  Missouri University of S&T (December 2017)  

  [B.S. Engineering Management](https://www.westpoint.edu/academics/majors-and-minors/engineering-management-major)  
  United States Military Academy(May 2013)

  
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71

