title: Austin McGahan # your name (or website title) here
logo: images/profile_photo.jpg?raw=True # your photo (or logo) here
description: >
  **Operations Research Analyst**  
  [M.S. Operations Research](https://nps.edu/web/or/operations-analysis-360)  
  *(June 2024)*  
  Naval Postgraduate School  

  [M.S. Engineering Management](https://emse.mst.edu/academicprograms/engineeringmanagement/graduate/)  
  *(December 2017)*  
  Missouri University of S&T  

  [B.S. Engineering Management](https://www.westpoint.edu/academics/majors-and-minors/engineering-management-major)  
  *(May 2013)*  
  United States Military Academy

  
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71
