title: Austin McGahan # your name (or website title) here
logo: images/profile_photo.jpg?raw=True # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Operations Research Analyst <br>
  <a href="https://nps.edu/web/or/operations-analysis-360">M.S. Operations Research</a> <br>
  (June 2024) <br>
  Naval Postgraduate School, Monterey, CA

  <a href="https://emse.mst.edu/academicprograms/engineeringmanagement/graduate/">M.S. Engineering Management</a> <br>
  (December 2017) <br>
  Missouri University of Science and Technology, Rolla, MO

  <a href="https://www.westpoint.edu/academics/majors-and-minors/engineering-management-major">B.S. Engineering Management</a> <br>
  (May 2013) <br>
  United States Military Academy, West Point, NY

  
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71
